Document: pygrep
Title: Debian pygrep Manual
Author: <insert document author here>
Abstract: This manual describes what pygrep is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pygrep/pygrep.sgml.gz

Format: postscript
Files: /usr/share/doc/pygrep/pygrep.ps.gz

Format: text
Files: /usr/share/doc/pygrep/pygrep.text.gz

Format: HTML
Index: /usr/share/doc/pygrep/html/index.html
Files: /usr/share/doc/pygrep/html/*.html
